# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_load_items_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='creator',
            field=models.CharField(default='Coffeehouse Chef', max_length=100),
        ),
    ]
