# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_load_stores_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': ('add',), 'permissions': (('give_refund', 'Can refund customers'), ('can_hire', 'Can hire employees'))},
        ),
    ]
